linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexty: 30
  misspwll:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - deadcode
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace